# Generated by Django 5.2.17 on 2026-10-03 20:46

from django.db import migrations, models

# The site moved from the indigo/cyan palette to a green theme: projects still using
# one of the old built-in colours get the matching green. Custom colours are kept.
OLD_TO_NEW = {"#6366f1": "#088650", "#6563f2": "#088650", "#5146e5": "#088650", "#06b6d4": "#0d9488"}


def recolor(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for old, new in OLD_TO_NEW.items():
        Project.objects.filter(color__iexact=old).update(color=new)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=models.CharField(default="#088650", max_length=9),
        ),
        migrations.RunPython(recolor, migrations.RunPython.noop),
    ]
