# Generated by Django 5.2.17 on 2026-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="reply_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
