# Generated by Django 5.2.17 on 2026-10-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("single", "Multiple choice (one answer)"),
                            ("multi", "Multiple choice (several answers)"),
                            ("true_false", "True / False"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Shown after submission when answers are revealed",
                    ),
                ),
                ("points", models.PositiveSmallIntegerField(default=1)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image or video shown with the question",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.CharField(blank=True, max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image option, e.g. 'select the correct segmentation'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.mediaasset",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("training", "Training test"),
                            ("feedback", "Feedback test"),
                            ("onboarding", "Onboarding test"),
                            ("qualification", "Qualification test"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveSmallIntegerField(
                        default=80, help_text="Percent required to pass"
                    ),
                ),
                (
                    "attempt_limit",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Empty = unlimited attempts", null=True
                    ),
                ),
                (
                    "time_limit_min",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Empty = no time limit", null=True
                    ),
                ),
                ("shuffle_questions", models.BooleanField(default=False)),
                (
                    "reveal_answers",
                    models.BooleanField(
                        default=True, help_text="Show correct answers after submission"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.test",
            ),
        ),
        migrations.CreateModel(
            name="TestAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assessments.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("test", "user"), name="uniq_test_assignment"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("points_earned", models.PositiveIntegerField(blank=True, null=True)),
                ("points_total", models.PositiveIntegerField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "submitted_at"],
                        name="assessments_user_id_6cbfb9_idx",
                    ),
                    models.Index(
                        fields=["test", "submitted_at"],
                        name="assessments_test_id_17d751_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("test", "user", "attempt_number"),
                        name="uniq_test_attempt",
                    )
                ],
            },
        ),
    ]
