# Generated by Django 5.2.17 on 2026-10-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testassignment",
            name="extra_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Attempts granted to this person on top of the test's attempt limit",
            ),
        ),
    ]
