# Generated by Django 5.2.17 on 2026-10-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("projects", "0001_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        editable=False, help_text="Displayed as #001", unique=True
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "explanation",
                    models.TextField(
                        help_text="Markdown: the correct way to handle this type of task"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("important", "Important"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("adhoc", "Ad-hoc"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to send to the whole project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="projects.team",
                    ),
                ),
                (
                    "test",
                    models.OneToOneField(
                        blank=True,
                        help_text="Short test employees take after watching",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="assessments.test",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "feedback",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("watched_ranges", models.JSONField(blank=True, default=list)),
                ("watched_seconds", models.FloatField(default=0)),
                ("percent", models.FloatField(default=0)),
                ("last_position_sec", models.FloatField(default=0)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "watched_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Video watched (or opened, if no video)",
                        null=True,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="feedback.feedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "watched_at"],
                        name="feedback_fe_user_id_3945d4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feedback", "user"), name="uniq_feedback_recipient"
                    )
                ],
            },
        ),
    ]
