# Generated by Django 5.2.17 on 2026-10-03 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Markdown supported — shown before the employee starts",
                    ),
                ),
                (
                    "range_start",
                    models.FloatField(
                        default=0,
                        help_text="Start of the 'hands present' range (seconds)",
                    ),
                ),
                (
                    "range_end",
                    models.FloatField(
                        blank=True,
                        help_text="End of the 'hands present' range (seconds). Empty = end of video",
                        null=True,
                    ),
                ),
                (
                    "reference_clips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Reference segmentation [[start, end], …]",
                    ),
                ),
                (
                    "tolerance_sec",
                    models.FloatField(
                        default=0.5,
                        help_text="Allowed boundary difference when scoring (seconds)",
                    ),
                ),
                ("passing_score", models.PositiveSmallIntegerField(default=80)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to make it available to every employee",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "In progress"), ("submitted", "Submitted")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("clips", models.JSONField(blank=True, default=list)),
                ("score", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("task_error", models.JSONField(blank=True, default=dict)),
                ("time_spent_sec", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="practice.practicetask",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "user", "status"],
                        name="practice_pr_task_id_46d63c_idx",
                    )
                ],
            },
        ),
    ]
