# Generated by Django 5.2.17 on 2026-10-04 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="practiceattempt",
            name="phase",
            field=models.CharField(
                choices=[
                    ("first", "Own work"),
                    ("correction", "Correction after the answer"),
                ],
                default="first",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="practicetask",
            name="answer_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="practicetask",
            name="answer_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Weekly review: when the reviewer's answer was released",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="practicetask",
            name="due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Weekly review: submit by this time (later submissions are marked late)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="practicetask",
            name="kind",
            field=models.CharField(
                choices=[
                    ("instant", "Instant score (trainer reference first)"),
                    (
                        "review",
                        "Weekly review (employees first, reviewer's answer later)",
                    ),
                ],
                default="instant",
                max_length=20,
            ),
        ),
    ]
