# Generated by Django 5.2.17 on 2026-10-03 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Bangla title shown to employees", max_length=200
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Title of the original English document (optional)",
                        max_length=200,
                        verbose_name="English title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the address, e.g. video-splitting",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One or two Bangla sentences shown on the guide card",
                        max_length=500,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="book-open-check",
                        help_text="Lucide icon name, e.g. scissors, file-text",
                        max_length=40,
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        choices=[
                            ("brand", "Indigo"),
                            ("cyan", "Cyan"),
                            ("emerald", "Emerald"),
                            ("amber", "Amber"),
                            ("rose", "Rose"),
                            ("violet", "Violet"),
                        ],
                        default="brand",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video_splitting", "Video splitting"),
                            ("description", "Description / text writing"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Shown to staff only",
                        max_length=500,
                        verbose_name="Original document link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to make it available to every employee",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guides",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="GuideSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.CharField(help_text="Bangla section title", max_length=200),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="English title"
                    ),
                ),
                (
                    "anchor",
                    models.SlugField(
                        help_text="Used for deep links (#anchor). Unique within the guide.",
                        max_length=120,
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="Optional Bangla introduction (Markdown)"
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="guides.guide",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="GuideStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.CharField(help_text="Bangla step title", max_length=200),
                ),
                (
                    "anchor",
                    models.SlugField(
                        help_text="Used for deep links (#anchor). Unique within the guide.",
                        max_length=120,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Bangla explanation (Markdown, callouts for rules / tips / warnings)",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(blank=True, verbose_name="Original English text"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="The ORIGINAL link (YouTube, Vimeo, Drive, Loom, Stream/SharePoint, Lark, MP4, HLS). Never re-hosted.",
                        max_length=1000,
                        verbose_name="Original video link",
                    ),
                ),
                ("video_caption", models.CharField(blank=True, max_length=300)),
                (
                    "video_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Start the video at this second (optional)",
                        null=True,
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"key": "N", "label_bn": "…", "description_bn": "…"}]',
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="guides.guide",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="guides.guidesection",
                    ),
                ),
            ],
            options={
                "ordering": ["section__order", "section_id", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="GuideProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="guides.guidestep",
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="guidesection",
            constraint=models.UniqueConstraint(
                fields=("guide", "anchor"), name="guides_section_anchor_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="guidestep",
            constraint=models.UniqueConstraint(
                fields=("guide", "anchor"), name="guides_step_anchor_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="guideprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "step"), name="guides_progress_user_step_unique"
            ),
        ),
    ]
