# Generated by Django 5.2.17 on 2026-10-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guidestep",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Where this step comes from, e.g. “Doc §2 Splitting rules, point 3 · video 01:20–02:05”. Staff only.",
                max_length=300,
                verbose_name="Source in the original",
            ),
        ),
        migrations.AddField(
            model_name="guidestep",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guidestep",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guidestep",
            name="video_end",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="End of the part of the video this step explains (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="accent",
            field=models.CharField(
                choices=[
                    ("brand", "Green (brand)"),
                    ("cyan", "Cyan"),
                    ("emerald", "Emerald"),
                    ("amber", "Amber"),
                    ("rose", "Rose"),
                    ("violet", "Violet"),
                ],
                default="brand",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GuideTaskError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "anchor",
                    models.SlugField(
                        help_text="Used for deep links (#anchor). Unique within the guide.",
                        max_length=120,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short Bangla name of the mistake", max_length=200
                    ),
                ),
                (
                    "what_wrong",
                    models.TextField(
                        help_text="Bangla (Markdown): exactly what was done wrong",
                        verbose_name="What went wrong",
                    ),
                ),
                (
                    "why_wrong",
                    models.TextField(
                        blank=True,
                        help_text="Bangla (Markdown): which rule it breaks and why",
                        verbose_name="Why it is wrong",
                    ),
                ),
                (
                    "how_to_avoid",
                    models.TextField(
                        blank=True,
                        help_text="Bangla (Markdown): what to check while working",
                        verbose_name="How to avoid it",
                    ),
                ),
                (
                    "correct_method",
                    models.TextField(
                        blank=True,
                        help_text="Bangla (Markdown): the right way, as the original shows it",
                        verbose_name="Correct method",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="The ORIGINAL video that shows this mistake (never re-hosted)",
                        max_length=1000,
                        verbose_name="Original video link",
                    ),
                ),
                ("video_start", models.PositiveIntegerField(blank=True, null=True)),
                ("video_end", models.PositiveIntegerField(blank=True, null=True)),
                ("video_caption", models.CharField(blank=True, max_length=300)),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="Where the original shows it, e.g. “Video 2 at 03:10” or “Doc §4 Task Error list”. Staff only.",
                        max_length=300,
                        verbose_name="Source in the original",
                    ),
                ),
                (
                    "source_text_en",
                    models.TextField(blank=True, verbose_name="Original English text"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_errors",
                        to="guides.guide",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        help_text="The step this mistake belongs to. Empty = a general example for the whole guide.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_errors",
                        to="guides.guidestep",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guide", "anchor"),
                        name="guides_task_error_anchor_unique",
                    )
                ],
            },
        ),
    ]
