# Generated by Django 5.2.17 on 2026-10-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_task_errors_and_verification"),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidestep",
            name="video_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="A video uploaded to our storage (used instead of the link when set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="storage.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="guidetaskerror",
            name="video_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="A video uploaded to our storage (used instead of the link when set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="storage.mediaasset",
            ),
        ),
    ]
