# Generated by Django 5.2.17 on 2026-10-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes — not visible to the sender"
            ),
        ),
    ]
